name: Build Test Deploy

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:
  #schedule:
  #  - cron: "0 */12 * * *" # Every 12 hours
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          path: "repo" # Use a different path to avoid nested directories
          submodules: "recursive" # Include submodules if present

      - name: Use Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: "npm"
          cache-dependency-path: "repo/06-CI-CD-in-Git-Hub-Actions/01-StudentRegistry/**/package-lock.json"

      - name: Build the app
        working-directory: "repo/06-CI-CD-in-Git-Hub-Actions/01-StudentRegistry"
        run: |
          npm install
      - name: Test the app
        working-directory: "repo/06-CI-CD-in-Git-Hub-Actions/01-StudentRegistry"
        run: |
          npm test
  # Render.com
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to production
        uses: johnbeynon/render-deploy-action@v0.0.8
        with:
          service-id: ${{ secrets.MY_RENDER_SERVICE_ID }}
          api-key: ${{ secrets.MY_RENDER_API_KEY }}
